; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bitslate_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_port = COM15
upload_speed = 115200
lib_deps = 
	lovyan03/LovyanGFX@^1.2.24
	lvgl/lvgl@^9.5.0
build_src_filter =
	+<main.cpp>
	+<hal/**>
	+<ui/screens/**>
	+<ui/navigation/**>
	+<apps/stem/**>
	+<apps/games/chess/lvgl/**>
	+<apps/geography/flags_quiz/lvgl/**>
	+<apps/geography/flags_quiz/generated/**>
	+<apps/geography/us_states_quiz/lvgl/**>
	+<apps/geography/us_states_quiz/core/**>
	-<apps/geography/us_states_quiz/core/test_*.cpp>
	+<apps/geography/us_states_quiz/generated/**>
	+<apps/bitblocks/**>
	+<assets/fonts/generated/**>
	+<assets/UI/home/*.c>
	+<assets/UI/home/*.h>
	+<assets/UI/bitblocks/generated/**>
	+<assets/images/chess/generated/**>
build_flags = 
	-DLV_CONF_INCLUDE_SIMPLE
	-DLV_CONF_PATH=\"lv_conf.h\"
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
	-Iinclude
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.partitions = huge_app.csv
