from __future__ import annotations

from pathlib import Path
from typing import List, Sequence, Tuple

from PIL import Image


ROOT = Path(__file__).resolve().parents[5]
SOURCE_IMAGE = ROOT / "src" / "apps" / "assets" / "images" / "geography" / "usa-map-unselected.png"
OUTPUT_MODULE = Path(__file__).resolve().parent / "generated_us_map.py"

GRID_WIDTH = 168
WHITE_THRESHOLD = 244
DARK_THRESHOLD = 120
MAP_COVERAGE_THRESHOLD = 0.12
BOUNDARY_COVERAGE_THRESHOLD = 0.08


def find_map_bounds(image: Image.Image) -> Tuple[int, int, int, int]:
    px = image.load()
    w, h = image.size
    xs: List[int] = []
    ys: List[int] = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a > 0 and (r < WHITE_THRESHOLD or g < WHITE_THRESHOLD or b < WHITE_THRESHOLD):
                xs.append(x)
                ys.append(y)

    if not xs or not ys:
        raise RuntimeError("Could not find non-background USA map pixels in source image.")

    return min(xs), min(ys), max(xs), max(ys)


def rows_for_width(bounds: Tuple[int, int, int, int], cols: int) -> int:
    min_x, min_y, max_x, max_y = bounds
    width = max_x - min_x + 1
    height = max_y - min_y + 1
    return max(1, round(cols * height / width))


def encode_rows(rows: Sequence[Sequence[int]]) -> List[str]:
    return ["".join(str(value) for value in row) for row in rows]


def build_masks(image: Image.Image, bounds: Tuple[int, int, int, int], cols: int, rows: int) -> Tuple[List[str], List[str], int, int]:
    min_x, min_y, max_x, max_y = bounds
    crop = image.crop((min_x, min_y, max_x + 1, max_y + 1)).convert("RGBA")
    crop_w, crop_h = crop.size
    px = crop.load()

    map_mask: List[List[int]] = []
    boundary_mask: List[List[int]] = []

    for row in range(rows):
        map_row: List[int] = []
        boundary_row: List[int] = []
        y0 = int(row * crop_h / rows)
        y1 = int((row + 1) * crop_h / rows)
        if y1 <= y0:
            y1 = min(crop_h, y0 + 1)

        for col in range(cols):
            x0 = int(col * crop_w / cols)
            x1 = int((col + 1) * crop_w / cols)
            if x1 <= x0:
                x1 = min(crop_w, x0 + 1)

            total = 0
            map_pixels = 0
            dark_pixels = 0

            for y in range(y0, y1):
                for x in range(x0, x1):
                    r, g, b, a = px[x, y]
                    total += 1
                    if a > 0 and (r < WHITE_THRESHOLD or g < WHITE_THRESHOLD or b < WHITE_THRESHOLD):
                        map_pixels += 1
                    if a > 0 and r < DARK_THRESHOLD and g < DARK_THRESHOLD and b < DARK_THRESHOLD:
                        dark_pixels += 1

            coverage = map_pixels / total if total else 0.0
            dark_coverage = dark_pixels / total if total else 0.0
            is_map = 1 if coverage >= MAP_COVERAGE_THRESHOLD else 0
            is_boundary = 1 if is_map and dark_coverage >= BOUNDARY_COVERAGE_THRESHOLD else 0

            map_row.append(is_map)
            boundary_row.append(is_boundary)

        map_mask.append(map_row)
        boundary_mask.append(boundary_row)

    return encode_rows(map_mask), encode_rows(boundary_mask), crop_w, crop_h


def write_module(
    output_path: Path,
    *,
    cols: int,
    rows: int,
    crop_width: int,
    crop_height: int,
    bounds: Tuple[int, int, int, int],
    map_mask: Sequence[str],
    boundary_mask: Sequence[str],
) -> None:
    min_x, min_y, max_x, max_y = bounds
    lines = [
        "# Auto-generated by generate_us_map_asset.py",
        "from __future__ import annotations",
        "",
        f"SOURCE_IMAGE = {SOURCE_IMAGE.name!r}",
        f"SOURCE_SIZE = {(1010, 676)!r}",
        f"SOURCE_BOUNDS = {(min_x, min_y, max_x, max_y)!r}",
        f"GRID_WIDTH = {cols}",
        f"GRID_HEIGHT = {rows}",
        f"CROP_WIDTH = {crop_width}",
        f"CROP_HEIGHT = {crop_height}",
        "BASE_COLOR = (193, 176, 118)",
        "BOUNDARY_COLOR = (55, 55, 55)",
        "BACKGROUND_COLOR = (247, 246, 241)",
        "CELL_MASK = [",
    ]
    lines.extend(f"    {row!r}," for row in map_mask)
    lines.extend(
        [
            "]",
            "BOUNDARY_MASK = [",
        ]
    )
    lines.extend(f"    {row!r}," for row in boundary_mask)
    lines.extend(
        [
            "]",
            "",
            "MAP_CELL_COUNT = sum(row.count('1') for row in CELL_MASK)",
            "BOUNDARY_CELL_COUNT = sum(row.count('1') for row in BOUNDARY_MASK)",
            "",
        ]
    )
    output_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    image = Image.open(SOURCE_IMAGE).convert("RGBA")
    bounds = find_map_bounds(image)
    rows = rows_for_width(bounds, GRID_WIDTH)
    map_mask, boundary_mask, crop_w, crop_h = build_masks(image, bounds, GRID_WIDTH, rows)
    write_module(
        OUTPUT_MODULE,
        cols=GRID_WIDTH,
        rows=rows,
        crop_width=crop_w,
        crop_height=crop_h,
        bounds=bounds,
        map_mask=map_mask,
        boundary_mask=boundary_mask,
    )

    map_cells = sum(row.count("1") for row in map_mask)
    boundary_cells = sum(row.count("1") for row in boundary_mask)
    print(f"Generated {OUTPUT_MODULE}")
    print(f"Grid: {GRID_WIDTH}x{rows}")
    print(f"Map cells: {map_cells}")
    print(f"Boundary cells: {boundary_cells}")
    print(f"Bounds: {bounds}")


if __name__ == "__main__":
    main()
